function _f(uuenc) {
  return {
    width : 30, height : 64, bpp : 1,
    transparent : 0,
    buffer : E.toArrayBuffer(atob(uuenc))
  };
}

const font={
   M: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAfgPgAfgfwAfgfwA/gd4A7gd4B7gc4Bzgc8Bzgc8DzgccDjgceDjgceHjgcOHDgcPHDwcHODwcHuDwcHuDwcD8DwcD8DwcD8DwcB4DwcB4DwcAADwcAADwcAADw8AADw8AADw8AADw8AADw8AADw8AADw8AADw8AADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  e: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAA//AAB//wAD8P4AHwD4APgB8APAA8AfAA+AeAA+AeAAeA+AAeA+AA+A///+A///+A///+A+AAAA+AAAAeAAAAeAAAAfAAAAfgAAAPwAAAP8AEAH//8AD//8AA//8AAH+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  r: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AA8H/gA8P/wA8//4A98H4A/4D4A/wB8A/gB8A/AB8A+AB8A+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  y: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfAAHgfAAPgPAAPAPgAPAPgAfAHgAeAHwA+ADwA+AD4A8AD4B8AB4B4AB8B4AA8D4AA8DwAA+DwAAeHgAAfHgAAPHgAAPPAAAPvAAAH/AAAH+AAAD+AAAD8AAAD8AAAB8AAAD4AAAD4AAAHwAAAPwAAAPgAAA/AAAD/AAA/+AAA/4AAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  C: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAP/+AAf/+AB//+AD/AOAD8ACAH4AAAPwAAAPgAAAPAAAAfAAAAfAAAAeAAAAeAAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAAeAAAAfAAAAfAAAAfAAAAPgAAAPgAAAPwAAAH8ACAD+AOAB//+AA//+AAP/+AAB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  h: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAA8AAAA8AAAA8AAAA8AAAA8AAAA8AAAA8AAAA8AAAA8AAAA8D4AA8P/AA8//gA9//wA/8PwA/wHwA/gD4A/AD4A+AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  i: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAfwAAAfwAAAfwAAAfwAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAf/gAAf/gAAf/gAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAHgAAAPwAA///4A///4A///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  s: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAB//gAH//gAP//gAfgAgAfAAAAeAAAAeAAAAfAAAAfgAAAfwAAAP+AAAH/wAAB/+AAAf/AAAD/gAAAfwAAAPwAAAHwAAADwAAADwAAAHwA4APwA///gA///AA//8AAB/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  t: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAfAAA///+A///+A///+AAfAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPAAAAPgAAAPwCAAH/+AAH/+AAB/+AAAP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  m: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOA8A8/j+A8/j+A9/n/A9j+PA/j+PA/D8PA+D8PA+D4PA+D4PA8DwPA8DwPA8DwPA8DwPA8DwPA8DwPA8DwPA8DwPA8DwPA8DwPA8DwPA8DwPA8DwPA8DwPA8DwPA8DwPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  P: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//4AA///AA///gA+A/wA+AP4A+AD4A+AB8A+AB8A+AA8A+AA8A+AA8A+AA8A+AB8A+AB8A+AD4A+AD4A+APwA+A/wA///gA//+AA//4AA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  n: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AA8P/AA8//gA9//wA/4PwA/wHwA/gD4A/AD4A+AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4A8AB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  d: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAA8AAAA8AAAA8AAAA8AAAA8AAAA8AAAA8AAAA8AAAA8AAD98AA//8AB//8AD+H8AHwB8APgA8APAA8AfAA8AeAA8AeAA8A+AA8A+AA8A+AA8A+AA8A+AA8A+AA8A+AA8A+AB8AeAD8AfAD8AfAH8AfgP8APw+8AP/88AH/48AD/w8AAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
  a: _f("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAD//AAP//wAP//wAPAP4AIAD4AAAB8AAAB8AAAB8AAAB8AAAB8AAP/8AD//8AH//8AP4B8AfgB8AfAB8A+AB8A+AB8A+AB8A+AH8A/AP8Afg/8Af/+8AP/88AH/w8AA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
};

const text="Merry Christmas Mr Pineda";

var vx=-128;
const w=30;

function run(g) {
  g.clear();

  var p=0;
  while ( (p+1) * w < vx ) {
    p++;
  }
  var off=vx-p*w;
  for ( var n=p; n< text.length; n++ ) {
    var f=font[text.charAt(n)];
    var x=(n-p)*w-off;
    if ( f ) {
      g.drawImage(f, x, 0);
    }
    if ( x + w > 128 ) {
      break;
    }
  }

  g.flip();
}

function cycle(g) {
  setInterval(function() {
    run(g);
    vx++;
    if ( vx > text.length * 30 ) {
      vx=-128; // wrap around
    }
  }, 1);
}

// SPI
function init() { 
  var s = new SPI();
  s.setup({mosi: D17 /* D1 */, sck:D16 /* D0 */});
  var g = require("SSD1306")
    .connectSPI(s, D19 /* DC */, D18 /* RST */, 
                function() { cycle(g); }, { cs : D23 });
}

init();
